[build]
target = "./index.html"
dist = "../dist"

[watch]
# ignore = ["./src-tauri", "./rym_backend"]

[serve]
address = "0.0.0.0"
port = 1420
open = false
proxy_ws = false
no_autoreload = true

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i ./styles/tailwind.css -o ../dist/.stage/index.css"]

[[proxy]]
rewrite = "/api/v1/"
backend = "http://0.0.0.0:5001/api/v1/"
